[package]
name = "flurl"
version = "0.2.3"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
hyper-tls = "*"
lazy_static = "*"

hyper-native-tls = "*"
native-tls = "*"
tokio-native-tls = "*"
