[package]
name = "flurl"
version = "0.3.0"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2021"


[features]
default = []
with-native-tls = ["hyper-native-tls", "native-tls", "tokio-native-tls"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }

rust-extensions = { tag = "0.1.3", git = "https://github.com/MyJetTools/rust-extensions.git" }

hyper-tls = "*"
lazy_static = "*"
async-trait = "*"
hyper-native-tls = { version = "*", optional = true }
native-tls = { version = "*", optional = true }
tokio-native-tls = { version = "*", optional = true }
