[package]
name = "flurl"
version = "0.2.3"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []

[dependencies]
rust-extensions = { tag = "0.1.2", git = "https://github.com/MyJetTools/rust-extensions.git" }

hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
hyper-tls = "*"
lazy_static = "*"
