[package]
name = "fl-url"
version = "0.1.0"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper-tls = "0.5.0"
hyper = { version = "0.14", features = ["full"] }
lazy_static = "*"
