[package]
name = "flurl"
version = "0.1.3"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-telemetry = { branch = "main", git = "https://github.com/MyJetTools/my-telemetry.git" }
hyper-tls = "*"
hyper = { version = "*", features = ["full"] }
lazy_static = "*"
tokio = { version = "*", features = ["full"] }
