[package]
name = "flurl"
version = "0.4.0"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2021"

[features]
default = []
support-unix-socket = ["hyper-unix-connector"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }

rust-extensions = { tag = "0.1.3", git = "https://github.com/MyJetTools/rust-extensions.git" }

lazy_static = "*"
async-trait = "*"

serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
hyper-rustls = { version = "*" }
rustls = { version = "*" }
openssl = { version = "*" }
hyper-unix-connector = { version = "*", optional = true }
