[package]
name = "flurl"
version = "0.1.0"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-telemetry = { branch = "main", git = "https://github.com/MyJetTools/my-telemetry.git" }
hyper-tls = "0.5.0"
hyper = { version = "0.14", features = ["full"] }
lazy_static = "*"
