[package]
name = "unix-sockets"
version = "0.5.0-rc01"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper-unix-connector = { version = "*" }
hyper = { version = "0.14.27", features = ["full"] }
